### ISSUE TITLE
Incorrect start index when launch bot after host goes forward

### ISSUE THREAD

**Issue by Klim-Karma** [enovikov11/political-quiz-bot#5]
I've launched bot after 10 mins of live translation started. Bot sends me question #5. Once I answered on it, bot sends me question #1.
I think each new session should start from question #1 independently from host position.

**Comment by enovikov11** [comment]
это ожидаемое поведение, пока идет стрим выдается актуальный вопрос, а если он отвечен, выдаются другие доступные, но не дальше отвеченного администратором

this is the expected behavior, while the stream is in progress, the current question is issued, and if it is answered, other available ones are displayed, but no further than the one answered by the administrator
